<?xml version="1.0" encoding="utf-8"?><Database Name="TRAYECTORIA_ESCOLAR" Class="DataClassesTrayectoriaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=148.227.28.3;Initial Catalog=TRAYECTORIA_ESCOLAR;Persist Security Info=True;User ID=sa" SettingsObjectName="DAC.Properties.Settings" SettingsPropertyName="TRAYECTORIA_ESCOLARConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.calificaciones3" Member="calificaciones3">
    <Type Name="calificaciones3">
      <Column Name="id_calificacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="folio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cuenta" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="calificacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.folios_ordinarios" Member="folios_ordinarios">
    <Type Name="folios_ordinarios">
      <Column Name="folio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cohorte" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="periodo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="grupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="carrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maestro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Materias" Member="Materias">
    <Type Name="Materias">
      <Column Name="idMateria" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idSemestre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreMateria" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idCarrera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Maestros" Member="Maestros">
    <Type Name="Maestros">
      <Column Name="id_maestro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_maestro" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Estado" Member="Estado">
    <Type Name="Estado">
      <Column Name="id_estado" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Municipio" Member="Municipio">
    <Type Name="Municipio">
      <Column Name="id_municipio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre_municipio" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Preparatorias" Member="Preparatorias">
    <Type Name="Preparatorias">
      <Column Name="idPreparatoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombrePreparatoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Regimen" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UAS" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VFolios_ordinarios" Member="VFolios_ordinarios">
    <Type Name="VFolios_ordinarios">
      <Column Name="FOLIO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="COHORTE" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="SEMESTRE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GRUPO" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MATERIA" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MAESTRO" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TIPO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Alumno" Member="Alumno">
    <Type Name="Alumno">
      <Column Name="numCuenta" Type="System.String" DbType="VarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NombreAlumno" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idCarrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sexo" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="fecha_ingreso" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="turno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PromedioPreparatoria" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Ceneval" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="idPreparatoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CURP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Seguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoSeguro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LugarOrigen" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="idMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="tutor" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="direccionTutor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="telefonoTutor" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="idPrepa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idSemestre" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Promedio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Cohorte" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="desertor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="rezagado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="baja" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GrupoCarrera" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Titulado" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Egresado" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Eficiencia_titulacion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Servicio_social" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Practicas" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.folios_extras" Member="folios_extras">
    <Type Name="folios_extras">
      <Column Name="folio" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cohorte" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="periodo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="grupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="carrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="materia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="maestro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewAlumnos" Member="ViewAlumnos">
    <Type Name="ViewAlumnos">
      <Column Name="CUENTA" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cohorte" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SEMESTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRUPO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARRERA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="turno" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="desertor" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="baja" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="rezagado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Titulado" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Egresado" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Eficiencia_titulacion" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Servicio_social" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Practicas" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="GrupoCarrera" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ReprobadosFoliosOrdinarios" Member="ReprobadosFoliosOrdinarios">
    <Type Name="ReprobadosFoliosOrdinarios">
      <Column Name="cuenta" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="calificacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="folio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="carrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="periodo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="materia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cohorte" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="grupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.cal_extras" Member="cal_extras">
    <Type Name="cal_extras">
      <Column Name="id_calificacion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="folio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cuenta" Type="System.String" DbType="VarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="calificacion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoGrupoSexo" Member="IngresoGrupoSexo">
    <Type Name="IngresoGrupoSexo">
      <Column Name="CATEGORIA" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CANTIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoEdadGrupo1" Member="IngresoEdadGrupo1">
    <Type Name="IngresoEdadGrupo1">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="edad_rango" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoEdadGrupo2" Member="IngresoEdadGrupo2">
    <Type Name="IngresoEdadGrupo2">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="edad_rango" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoEdadGrupo3" Member="IngresoEdadGrupo3">
    <Type Name="IngresoEdadGrupo3">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="edad_rango" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoInstitucionEducativa" Member="IngresoInstitucionEducativa">
    <Type Name="IngresoInstitucionEducativa">
      <Column Name="NombrePreparatoria" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoLugarProcedenciaGrupo1" Member="IngresoLugarProcedenciaGrupo1">
    <Type Name="IngresoLugarProcedenciaGrupo1">
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoLugarProcedenciaGrupo2" Member="IngresoLugarProcedenciaGrupo2">
    <Type Name="IngresoLugarProcedenciaGrupo2">
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoLugarProcedenciaGrupo3" Member="IngresoLugarProcedenciaGrupo3">
    <Type Name="IngresoLugarProcedenciaGrupo3">
      <Column Name="nombre" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoPromedioGrupo1" Member="IngresoPromedioGrupo1">
    <Type Name="IngresoPromedioGrupo1">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedio" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoPromedioGrupo2" Member="IngresoPromedioGrupo2">
    <Type Name="IngresoPromedioGrupo2">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedio" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoPromedioGrupo3" Member="IngresoPromedioGrupo3">
    <Type Name="IngresoPromedioGrupo3">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="promedio" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoCenevalGrupo1" Member="IngresoCenevalGrupo1">
    <Type Name="IngresoCenevalGrupo1">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromedioCeneval" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoCenevalGrupo2" Member="IngresoCenevalGrupo2">
    <Type Name="IngresoCenevalGrupo2">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromedioCeneval" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoCenevalGrupo3" Member="IngresoCenevalGrupo3">
    <Type Name="IngresoCenevalGrupo3">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromedioCeneval" Type="System.String" DbType="VarChar(18)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IngresoCarrera" Member="IngresoCarrera">
    <Type Name="IngresoCarrera">
      <Column Name="CARRERA" Type="System.String" DbType="VarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="CANTIDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DesercionGrupoCohorte" Member="DesercionGrupoCohorte">
    <Type Name="DesercionGrupoCohorte">
      <Column Name="[Cohorte y Grupo]" Member="Cohorte_y_Grupo" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DesercionGrupoSexo" Member="DesercionGrupoSexo">
    <Type Name="DesercionGrupoSexo">
      <Column Name="[Sexo y Grupo]" Member="Sexo_y_Grupo" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RezagadosGrupoCohorte" Member="RezagadosGrupoCohorte">
    <Type Name="RezagadosGrupoCohorte">
      <Column Name="[Cohorte y Grupo]" Member="Cohorte_y_Grupo" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RezagadosGrupoSexo" Member="RezagadosGrupoSexo">
    <Type Name="RezagadosGrupoSexo">
      <Column Name="[Sexo y Grupo]" Member="Sexo_y_Grupo" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ins_calificacion" Method="ins_calificacion">
    <Parameter Name="folio" Type="System.Int32" DbType="Int" />
    <Parameter Name="cuenta" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="calificacion" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ins_folios_ord" Method="ins_folios_ord">
    <Parameter Name="folio" Type="System.Int32" DbType="Int" />
    <Parameter Name="cohorte" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="periodo" Type="System.Int32" DbType="Int" />
    <Parameter Name="grupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="carrera" Type="System.Int32" DbType="Int" />
    <Parameter Name="materia" Type="System.Int32" DbType="Int" />
    <Parameter Name="maestro" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EditAlumno" Method="EditAlumno">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="grupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="promprepa" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="ceneval" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="fecha_ingreso" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="turno" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="fecha_nacimiento" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="celular" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RFC" Parameter="rFC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CURP" Parameter="cURP" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="semestre" Type="System.Int32" DbType="Int" />
    <Parameter Name="cohorte" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="msg" Type="System.String" DbType="VarChar(100)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteAlumno" Method="DeleteAlumno">
    <Parameter Name="codigo" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Baja" Method="Baja">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Desertor" Method="Desertor">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insPreparatoria" Method="insPreparatoria">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="regimen" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="uas" Type="System.Char" DbType="Char(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insPreparatoria" Method="insPreparatoria1">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="regimen" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="uas" Type="System.Char" DbType="Char(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insAlumno" Method="insAlumno">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="grupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="carrera" Type="System.Int32" DbType="Int" />
    <Parameter Name="sexo" Type="System.Char" DbType="Char(1)" />
    <Parameter Name="promprepa" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="ceneval" Type="System.Decimal" DbType="Decimal(10,2)" />
    <Parameter Name="fecha_ingreso" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="turno" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="prepa" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha_nacimiento" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="celular" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="correo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="RFC" Parameter="rFC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CURP" Parameter="cURP" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Seguro" Parameter="seguro" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tipoSeguro" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="lugar_origen" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="municipio" Type="System.Int32" DbType="Int" />
    <Parameter Name="direccion" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="tutor" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="dire_tutor" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="tel_tutor" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="semestre" Type="System.Int32" DbType="Int" />
    <Parameter Name="promedio" Type="System.Int32" DbType="Int" />
    <Parameter Name="cohorte" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EditAlumnoBasico" Method="EditAlumnoBasico">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="cuentanew" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(80)" />
    <Parameter Name="grupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="turno" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="semestre" Type="System.Int32" DbType="Int" />
    <Parameter Name="cohorte" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="carrera" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Rezago" Method="Rezago">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Egresado" Method="Egresado">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Titulado" Method="Titulado">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.EficienciaTitulacion" Method="EficienciaTitulacion">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ServicioSocial" Method="ServicioSocial">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PracticasProfesionales" Method="PracticasProfesionales">
    <Parameter Name="numcuenta" Type="System.String" DbType="VarChar(9)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ins_folios_ext" Method="ins_folios_ext">
    <Parameter Name="folio" Type="System.Int32" DbType="Int" />
    <Parameter Name="cohorte" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="periodo" Type="System.Int32" DbType="Int" />
    <Parameter Name="grupo" Type="System.Int32" DbType="Int" />
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="carrera" Type="System.Int32" DbType="Int" />
    <Parameter Name="materia" Type="System.Int32" DbType="Int" />
    <Parameter Name="maestro" Type="System.Int32" DbType="Int" />
    <Parameter Name="tipo" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ins_calificacion_extra" Method="ins_calificacion_extra">
    <Parameter Name="folio" Type="System.Int32" DbType="Int" />
    <Parameter Name="cuenta" Type="System.String" DbType="VarChar(9)" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="calificacion" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
</Database>