#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TRAYECTORIA_ESCOLAR")]
	public partial class DataClassesTrayectoriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcalificaciones3(calificaciones3 instance);
    partial void Updatecalificaciones3(calificaciones3 instance);
    partial void Deletecalificaciones3(calificaciones3 instance);
    partial void Insertfolios_ordinarios(folios_ordinarios instance);
    partial void Updatefolios_ordinarios(folios_ordinarios instance);
    partial void Deletefolios_ordinarios(folios_ordinarios instance);
    partial void InsertMaterias(Materias instance);
    partial void UpdateMaterias(Materias instance);
    partial void DeleteMaterias(Materias instance);
    partial void InsertMaestros(Maestros instance);
    partial void UpdateMaestros(Maestros instance);
    partial void DeleteMaestros(Maestros instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertMunicipio(Municipio instance);
    partial void UpdateMunicipio(Municipio instance);
    partial void DeleteMunicipio(Municipio instance);
    partial void InsertPreparatorias(Preparatorias instance);
    partial void UpdatePreparatorias(Preparatorias instance);
    partial void DeletePreparatorias(Preparatorias instance);
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void Insertfolios_extras(folios_extras instance);
    partial void Updatefolios_extras(folios_extras instance);
    partial void Deletefolios_extras(folios_extras instance);
    partial void Insertcal_extras(cal_extras instance);
    partial void Updatecal_extras(cal_extras instance);
    partial void Deletecal_extras(cal_extras instance);
    #endregion
		
		public DataClassesTrayectoriaDataContext() : 
				base(global::DAC.Properties.Settings.Default.TRAYECTORIA_ESCOLARConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTrayectoriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTrayectoriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTrayectoriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesTrayectoriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<calificaciones3> calificaciones3
		{
			get
			{
				return this.GetTable<calificaciones3>();
			}
		}
		
		public System.Data.Linq.Table<folios_ordinarios> folios_ordinarios
		{
			get
			{
				return this.GetTable<folios_ordinarios>();
			}
		}
		
		public System.Data.Linq.Table<Materias> Materias
		{
			get
			{
				return this.GetTable<Materias>();
			}
		}
		
		public System.Data.Linq.Table<Maestros> Maestros
		{
			get
			{
				return this.GetTable<Maestros>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estado
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<Municipio> Municipio
		{
			get
			{
				return this.GetTable<Municipio>();
			}
		}
		
		public System.Data.Linq.Table<Preparatorias> Preparatorias
		{
			get
			{
				return this.GetTable<Preparatorias>();
			}
		}
		
		public System.Data.Linq.Table<VFolios_ordinarios> VFolios_ordinarios
		{
			get
			{
				return this.GetTable<VFolios_ordinarios>();
			}
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<folios_extras> folios_extras
		{
			get
			{
				return this.GetTable<folios_extras>();
			}
		}
		
		public System.Data.Linq.Table<ViewAlumnos> ViewAlumnos
		{
			get
			{
				return this.GetTable<ViewAlumnos>();
			}
		}
		
		public System.Data.Linq.Table<ReprobadosFoliosOrdinarios> ReprobadosFoliosOrdinarios
		{
			get
			{
				return this.GetTable<ReprobadosFoliosOrdinarios>();
			}
		}
		
		public System.Data.Linq.Table<cal_extras> cal_extras
		{
			get
			{
				return this.GetTable<cal_extras>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_calificacion")]
		public int ins_calificacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> folio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string cuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), folio, cuenta, nombre, calificacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_folios_ord")]
		public int ins_folios_ord([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> folio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cohorte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grupo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> materia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maestro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), folio, cohorte, periodo, grupo, fecha, carrera, materia, maestro, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditAlumno")]
		public int EditAlumno(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string nombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grupo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sexo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> promprepa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> ceneval, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_ingreso, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string turno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_nacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string celular, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFC", DbType="VarChar(50)")] string rFC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURP", DbType="VarChar(50)")] string cURP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semestre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cohorte, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] ref string msg)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta, nombre, grupo, sexo, promprepa, ceneval, fecha_ingreso, turno, fecha_nacimiento, telefono, celular, correo, rFC, cURP, semestre, cohorte, direccion, msg);
			msg = ((string)(result.GetParameterValue(17)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteAlumno")]
		public int DeleteAlumno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string codigo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Baja")]
		public int Baja([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Desertor")]
		public int Desertor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insPreparatoria")]
		public int insPreparatoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string regimen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> uas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, regimen, uas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insPreparatoria")]
		public int insPreparatoria1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string regimen, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> uas)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, regimen, uas);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insAlumno")]
		public int insAlumno(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string nombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grupo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carrera, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(1)")] System.Nullable<char> sexo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> promprepa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> ceneval, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_ingreso, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string turno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prepa, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallDateTime")] System.Nullable<System.DateTime> fecha_nacimiento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string celular, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string correo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFC", DbType="VarChar(50)")] string rFC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CURP", DbType="VarChar(50)")] string cURP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Seguro", DbType="VarChar(50)")] string seguro, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tipoSeguro, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lugar_origen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> municipio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string tutor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string dire_tutor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string tel_tutor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semestre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> promedio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cohorte)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta, nombre, grupo, carrera, sexo, promprepa, ceneval, fecha_ingreso, turno, prepa, fecha_nacimiento, telefono, celular, correo, rFC, cURP, seguro, tipoSeguro, lugar_origen, municipio, direccion, tutor, dire_tutor, tel_tutor, semestre, promedio, cohorte);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditAlumnoBasico")]
		public int EditAlumnoBasico([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string cuentanew, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(80)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grupo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string turno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> semestre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cohorte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carrera)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta, cuentanew, nombre, grupo, turno, semestre, cohorte, carrera);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Rezago")]
		public int Rezago([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Egresado")]
		public int Egresado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Titulado")]
		public int Titulado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EficienciaTitulacion")]
		public int EficienciaTitulacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ServicioSocial")]
		public int ServicioSocial([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PracticasProfesionales")]
		public int PracticasProfesionales([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string numcuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numcuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_folios_ext")]
		public int ins_folios_ext([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> folio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string cohorte, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> periodo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grupo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> carrera, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> materia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maestro, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string tipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), folio, cohorte, periodo, grupo, fecha, carrera, materia, maestro, tipo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ins_calificacion_extra")]
		public int ins_calificacion_extra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> folio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(9)")] string cuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> calificacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), folio, cuenta, nombre, calificacion);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.calificaciones3")]
	public partial class calificaciones3 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_calificacion;
		
		private int _folio;
		
		private string _cuenta;
		
		private string _nombre;
		
		private double _calificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_calificacionChanging(int value);
    partial void Onid_calificacionChanged();
    partial void OnfolioChanging(int value);
    partial void OnfolioChanged();
    partial void OncuentaChanging(string value);
    partial void OncuentaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncalificacionChanging(double value);
    partial void OncalificacionChanged();
    #endregion
		
		public calificaciones3()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_calificacion
		{
			get
			{
				return this._id_calificacion;
			}
			set
			{
				if ((this._id_calificacion != value))
				{
					this.Onid_calificacionChanging(value);
					this.SendPropertyChanging();
					this._id_calificacion = value;
					this.SendPropertyChanged("id_calificacion");
					this.Onid_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int NOT NULL")]
		public int folio
		{
			get
			{
				return this._folio;
			}
			set
			{
				if ((this._folio != value))
				{
					this.OnfolioChanging(value);
					this.SendPropertyChanging();
					this._folio = value;
					this.SendPropertyChanged("folio");
					this.OnfolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string cuenta
		{
			get
			{
				return this._cuenta;
			}
			set
			{
				if ((this._cuenta != value))
				{
					this.OncuentaChanging(value);
					this.SendPropertyChanging();
					this._cuenta = value;
					this.SendPropertyChanged("cuenta");
					this.OncuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Float NOT NULL")]
		public double calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.folios_ordinarios")]
	public partial class folios_ordinarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _folio;
		
		private string _cohorte;
		
		private int _periodo;
		
		private int _grupo;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _carrera;
		
		private System.Nullable<int> _materia;
		
		private System.Nullable<int> _maestro;
		
		private string _tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfolioChanging(int value);
    partial void OnfolioChanged();
    partial void OncohorteChanging(string value);
    partial void OncohorteChanged();
    partial void OnperiodoChanging(int value);
    partial void OnperiodoChanged();
    partial void OngrupoChanging(int value);
    partial void OngrupoChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OncarreraChanging(System.Nullable<int> value);
    partial void OncarreraChanged();
    partial void OnmateriaChanging(System.Nullable<int> value);
    partial void OnmateriaChanged();
    partial void OnmaestroChanging(System.Nullable<int> value);
    partial void OnmaestroChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public folios_ordinarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int folio
		{
			get
			{
				return this._folio;
			}
			set
			{
				if ((this._folio != value))
				{
					this.OnfolioChanging(value);
					this.SendPropertyChanging();
					this._folio = value;
					this.SendPropertyChanged("folio");
					this.OnfolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cohorte", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cohorte
		{
			get
			{
				return this._cohorte;
			}
			set
			{
				if ((this._cohorte != value))
				{
					this.OncohorteChanging(value);
					this.SendPropertyChanging();
					this._cohorte = value;
					this.SendPropertyChanged("cohorte");
					this.OncohorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="Int NOT NULL")]
		public int periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this.OnperiodoChanging(value);
					this.SendPropertyChanging();
					this._periodo = value;
					this.SendPropertyChanged("periodo");
					this.OnperiodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="Int NOT NULL")]
		public int grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this.OngrupoChanging(value);
					this.SendPropertyChanging();
					this._grupo = value;
					this.SendPropertyChanged("grupo");
					this.OngrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrera", DbType="Int")]
		public System.Nullable<int> carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				if ((this._carrera != value))
				{
					this.OncarreraChanging(value);
					this.SendPropertyChanging();
					this._carrera = value;
					this.SendPropertyChanged("carrera");
					this.OncarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia", DbType="Int")]
		public System.Nullable<int> materia
		{
			get
			{
				return this._materia;
			}
			set
			{
				if ((this._materia != value))
				{
					this.OnmateriaChanging(value);
					this.SendPropertyChanging();
					this._materia = value;
					this.SendPropertyChanged("materia");
					this.OnmateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro", DbType="Int")]
		public System.Nullable<int> maestro
		{
			get
			{
				return this._maestro;
			}
			set
			{
				if ((this._maestro != value))
				{
					this.OnmaestroChanging(value);
					this.SendPropertyChanging();
					this._maestro = value;
					this.SendPropertyChanged("maestro");
					this.OnmaestroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Materias")]
	public partial class Materias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMateria;
		
		private int _idSemestre;
		
		private string _NombreMateria;
		
		private int _idCarrera;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMateriaChanging(int value);
    partial void OnidMateriaChanged();
    partial void OnidSemestreChanging(int value);
    partial void OnidSemestreChanged();
    partial void OnNombreMateriaChanging(string value);
    partial void OnNombreMateriaChanged();
    partial void OnidCarreraChanging(int value);
    partial void OnidCarreraChanged();
    #endregion
		
		public Materias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMateria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idMateria
		{
			get
			{
				return this._idMateria;
			}
			set
			{
				if ((this._idMateria != value))
				{
					this.OnidMateriaChanging(value);
					this.SendPropertyChanging();
					this._idMateria = value;
					this.SendPropertyChanged("idMateria");
					this.OnidMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSemestre", DbType="Int NOT NULL")]
		public int idSemestre
		{
			get
			{
				return this._idSemestre;
			}
			set
			{
				if ((this._idSemestre != value))
				{
					this.OnidSemestreChanging(value);
					this.SendPropertyChanging();
					this._idSemestre = value;
					this.SendPropertyChanged("idSemestre");
					this.OnidSemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMateria", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreMateria
		{
			get
			{
				return this._NombreMateria;
			}
			set
			{
				if ((this._NombreMateria != value))
				{
					this.OnNombreMateriaChanging(value);
					this.SendPropertyChanging();
					this._NombreMateria = value;
					this.SendPropertyChanged("NombreMateria");
					this.OnNombreMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarrera", DbType="Int NOT NULL")]
		public int idCarrera
		{
			get
			{
				return this._idCarrera;
			}
			set
			{
				if ((this._idCarrera != value))
				{
					this.OnidCarreraChanging(value);
					this.SendPropertyChanging();
					this._idCarrera = value;
					this.SendPropertyChanged("idCarrera");
					this.OnidCarreraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maestros")]
	public partial class Maestros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_maestro;
		
		private string _nombre_maestro;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_maestroChanging(int value);
    partial void Onid_maestroChanged();
    partial void Onnombre_maestroChanging(string value);
    partial void Onnombre_maestroChanged();
    #endregion
		
		public Maestros()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_maestro", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_maestro
		{
			get
			{
				return this._id_maestro;
			}
			set
			{
				if ((this._id_maestro != value))
				{
					this.Onid_maestroChanging(value);
					this.SendPropertyChanging();
					this._id_maestro = value;
					this.SendPropertyChanged("id_maestro");
					this.Onid_maestroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_maestro", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_maestro
		{
			get
			{
				return this._nombre_maestro;
			}
			set
			{
				if ((this._nombre_maestro != value))
				{
					this.Onnombre_maestroChanging(value);
					this.SendPropertyChanging();
					this._nombre_maestro = value;
					this.SendPropertyChanged("nombre_maestro");
					this.Onnombre_maestroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_estado;
		
		private string _nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_estadoChanging(int value);
    partial void Onid_estadoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Estado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					this.Onid_estadoChanging(value);
					this.SendPropertyChanging();
					this._id_estado = value;
					this.SendPropertyChanged("id_estado");
					this.Onid_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(255)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Municipio")]
	public partial class Municipio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_municipio;
		
		private string _nombre_municipio;
		
		private int _estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_municipioChanging(int value);
    partial void Onid_municipioChanged();
    partial void Onnombre_municipioChanging(string value);
    partial void Onnombre_municipioChanged();
    partial void OnestadoChanging(int value);
    partial void OnestadoChanged();
    #endregion
		
		public Municipio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_municipio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_municipio
		{
			get
			{
				return this._id_municipio;
			}
			set
			{
				if ((this._id_municipio != value))
				{
					this.Onid_municipioChanging(value);
					this.SendPropertyChanging();
					this._id_municipio = value;
					this.SendPropertyChanged("id_municipio");
					this.Onid_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_municipio", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre_municipio
		{
			get
			{
				return this._nombre_municipio;
			}
			set
			{
				if ((this._nombre_municipio != value))
				{
					this.Onnombre_municipioChanging(value);
					this.SendPropertyChanging();
					this._nombre_municipio = value;
					this.SendPropertyChanged("nombre_municipio");
					this.Onnombre_municipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int NOT NULL")]
		public int estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Preparatorias")]
	public partial class Preparatorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPreparatoria;
		
		private string _NombrePreparatoria;
		
		private string _Regimen;
		
		private System.Nullable<char> _UAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPreparatoriaChanging(int value);
    partial void OnidPreparatoriaChanged();
    partial void OnNombrePreparatoriaChanging(string value);
    partial void OnNombrePreparatoriaChanged();
    partial void OnRegimenChanging(string value);
    partial void OnRegimenChanged();
    partial void OnUASChanging(System.Nullable<char> value);
    partial void OnUASChanged();
    #endregion
		
		public Preparatorias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPreparatoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idPreparatoria
		{
			get
			{
				return this._idPreparatoria;
			}
			set
			{
				if ((this._idPreparatoria != value))
				{
					this.OnidPreparatoriaChanging(value);
					this.SendPropertyChanging();
					this._idPreparatoria = value;
					this.SendPropertyChanged("idPreparatoria");
					this.OnidPreparatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePreparatoria", DbType="VarChar(50)")]
		public string NombrePreparatoria
		{
			get
			{
				return this._NombrePreparatoria;
			}
			set
			{
				if ((this._NombrePreparatoria != value))
				{
					this.OnNombrePreparatoriaChanging(value);
					this.SendPropertyChanging();
					this._NombrePreparatoria = value;
					this.SendPropertyChanged("NombrePreparatoria");
					this.OnNombrePreparatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Regimen", DbType="VarChar(20)")]
		public string Regimen
		{
			get
			{
				return this._Regimen;
			}
			set
			{
				if ((this._Regimen != value))
				{
					this.OnRegimenChanging(value);
					this.SendPropertyChanging();
					this._Regimen = value;
					this.SendPropertyChanged("Regimen");
					this.OnRegimenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAS", DbType="Char(1)")]
		public System.Nullable<char> UAS
		{
			get
			{
				return this._UAS;
			}
			set
			{
				if ((this._UAS != value))
				{
					this.OnUASChanging(value);
					this.SendPropertyChanging();
					this._UAS = value;
					this.SendPropertyChanged("UAS");
					this.OnUASChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VFolios_ordinarios")]
	public partial class VFolios_ordinarios
	{
		
		private int _FOLIO;
		
		private string _COHORTE;
		
		private int _SEMESTRE;
		
		private int _GRUPO;
		
		private string _MATERIA;
		
		private string _MAESTRO;
		
		private string _TIPO;
		
		public VFolios_ordinarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOLIO", DbType="Int NOT NULL")]
		public int FOLIO
		{
			get
			{
				return this._FOLIO;
			}
			set
			{
				if ((this._FOLIO != value))
				{
					this._FOLIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COHORTE", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string COHORTE
		{
			get
			{
				return this._COHORTE;
			}
			set
			{
				if ((this._COHORTE != value))
				{
					this._COHORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTRE", DbType="Int NOT NULL")]
		public int SEMESTRE
		{
			get
			{
				return this._SEMESTRE;
			}
			set
			{
				if ((this._SEMESTRE != value))
				{
					this._SEMESTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO", DbType="Int NOT NULL")]
		public int GRUPO
		{
			get
			{
				return this._GRUPO;
			}
			set
			{
				if ((this._GRUPO != value))
				{
					this._GRUPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATERIA", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MATERIA
		{
			get
			{
				return this._MATERIA;
			}
			set
			{
				if ((this._MATERIA != value))
				{
					this._MATERIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAESTRO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MAESTRO
		{
			get
			{
				return this._MAESTRO;
			}
			set
			{
				if ((this._MAESTRO != value))
				{
					this._MAESTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="VarChar(10)")]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this._TIPO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _numCuenta;
		
		private string _NombreAlumno;
		
		private System.Nullable<int> _idGrupo;
		
		private System.Nullable<int> _idCarrera;
		
		private System.Nullable<char> _Sexo;
		
		private System.Data.Linq.Binary _imagen;
		
		private System.Nullable<System.DateTime> _fecha_ingreso;
		
		private string _turno;
		
		private System.Nullable<decimal> _PromedioPreparatoria;
		
		private System.Nullable<decimal> _Ceneval;
		
		private System.Nullable<int> _idPreparatoria;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Correo;
		
		private string _RFC;
		
		private string _CURP;
		
		private string _Seguro;
		
		private string _TipoSeguro;
		
		private string _LugarOrigen;
		
		private System.Nullable<int> _idMunicipio;
		
		private string _Direccion;
		
		private string _tutor;
		
		private string _direccionTutor;
		
		private string _telefonoTutor;
		
		private System.Nullable<int> _idPrepa;
		
		private System.Nullable<int> _idSemestre;
		
		private System.Nullable<double> _Promedio;
		
		private string _Cohorte;
		
		private System.Nullable<bool> _desertor;
		
		private System.Nullable<bool> _rezagado;
		
		private System.Nullable<bool> _baja;
		
		private string _GrupoCarrera;
		
		private string _Titulado;
		
		private string _Egresado;
		
		private string _Eficiencia_titulacion;
		
		private string _Servicio_social;
		
		private string _Practicas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnumCuentaChanging(string value);
    partial void OnnumCuentaChanged();
    partial void OnNombreAlumnoChanging(string value);
    partial void OnNombreAlumnoChanged();
    partial void OnidGrupoChanging(System.Nullable<int> value);
    partial void OnidGrupoChanged();
    partial void OnidCarreraChanging(System.Nullable<int> value);
    partial void OnidCarreraChanged();
    partial void OnSexoChanging(System.Nullable<char> value);
    partial void OnSexoChanged();
    partial void OnimagenChanging(System.Data.Linq.Binary value);
    partial void OnimagenChanged();
    partial void Onfecha_ingresoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ingresoChanged();
    partial void OnturnoChanging(string value);
    partial void OnturnoChanged();
    partial void OnPromedioPreparatoriaChanging(System.Nullable<decimal> value);
    partial void OnPromedioPreparatoriaChanged();
    partial void OnCenevalChanging(System.Nullable<decimal> value);
    partial void OnCenevalChanged();
    partial void OnidPreparatoriaChanging(System.Nullable<int> value);
    partial void OnidPreparatoriaChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnRFCChanging(string value);
    partial void OnRFCChanged();
    partial void OnCURPChanging(string value);
    partial void OnCURPChanged();
    partial void OnSeguroChanging(string value);
    partial void OnSeguroChanged();
    partial void OnTipoSeguroChanging(string value);
    partial void OnTipoSeguroChanged();
    partial void OnLugarOrigenChanging(string value);
    partial void OnLugarOrigenChanged();
    partial void OnidMunicipioChanging(System.Nullable<int> value);
    partial void OnidMunicipioChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OntutorChanging(string value);
    partial void OntutorChanged();
    partial void OndireccionTutorChanging(string value);
    partial void OndireccionTutorChanged();
    partial void OntelefonoTutorChanging(string value);
    partial void OntelefonoTutorChanged();
    partial void OnidPrepaChanging(System.Nullable<int> value);
    partial void OnidPrepaChanged();
    partial void OnidSemestreChanging(System.Nullable<int> value);
    partial void OnidSemestreChanged();
    partial void OnPromedioChanging(System.Nullable<double> value);
    partial void OnPromedioChanged();
    partial void OnCohorteChanging(string value);
    partial void OnCohorteChanged();
    partial void OndesertorChanging(System.Nullable<bool> value);
    partial void OndesertorChanged();
    partial void OnrezagadoChanging(System.Nullable<bool> value);
    partial void OnrezagadoChanged();
    partial void OnbajaChanging(System.Nullable<bool> value);
    partial void OnbajaChanged();
    partial void OnGrupoCarreraChanging(string value);
    partial void OnGrupoCarreraChanged();
    partial void OnTituladoChanging(string value);
    partial void OnTituladoChanged();
    partial void OnEgresadoChanging(string value);
    partial void OnEgresadoChanged();
    partial void OnEficiencia_titulacionChanging(string value);
    partial void OnEficiencia_titulacionChanged();
    partial void OnServicio_socialChanging(string value);
    partial void OnServicio_socialChanged();
    partial void OnPracticasChanging(string value);
    partial void OnPracticasChanged();
    #endregion
		
		public Alumno()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numCuenta", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string numCuenta
		{
			get
			{
				return this._numCuenta;
			}
			set
			{
				if ((this._numCuenta != value))
				{
					this.OnnumCuentaChanging(value);
					this.SendPropertyChanging();
					this._numCuenta = value;
					this.SendPropertyChanged("numCuenta");
					this.OnnumCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreAlumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreAlumno
		{
			get
			{
				return this._NombreAlumno;
			}
			set
			{
				if ((this._NombreAlumno != value))
				{
					this.OnNombreAlumnoChanging(value);
					this.SendPropertyChanging();
					this._NombreAlumno = value;
					this.SendPropertyChanged("NombreAlumno");
					this.OnNombreAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idGrupo", DbType="Int")]
		public System.Nullable<int> idGrupo
		{
			get
			{
				return this._idGrupo;
			}
			set
			{
				if ((this._idGrupo != value))
				{
					this.OnidGrupoChanging(value);
					this.SendPropertyChanging();
					this._idGrupo = value;
					this.SendPropertyChanged("idGrupo");
					this.OnidGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCarrera", DbType="Int")]
		public System.Nullable<int> idCarrera
		{
			get
			{
				return this._idCarrera;
			}
			set
			{
				if ((this._idCarrera != value))
				{
					this.OnidCarreraChanging(value);
					this.SendPropertyChanging();
					this._idCarrera = value;
					this.SendPropertyChanged("idCarrera");
					this.OnidCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1)")]
		public System.Nullable<char> Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imagen", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imagen
		{
			get
			{
				return this._imagen;
			}
			set
			{
				if ((this._imagen != value))
				{
					this.OnimagenChanging(value);
					this.SendPropertyChanging();
					this._imagen = value;
					this.SendPropertyChanged("imagen");
					this.OnimagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ingreso", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_ingreso
		{
			get
			{
				return this._fecha_ingreso;
			}
			set
			{
				if ((this._fecha_ingreso != value))
				{
					this.Onfecha_ingresoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ingreso = value;
					this.SendPropertyChanged("fecha_ingreso");
					this.Onfecha_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno", DbType="VarChar(10)")]
		public string turno
		{
			get
			{
				return this._turno;
			}
			set
			{
				if ((this._turno != value))
				{
					this.OnturnoChanging(value);
					this.SendPropertyChanging();
					this._turno = value;
					this.SendPropertyChanged("turno");
					this.OnturnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromedioPreparatoria", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> PromedioPreparatoria
		{
			get
			{
				return this._PromedioPreparatoria;
			}
			set
			{
				if ((this._PromedioPreparatoria != value))
				{
					this.OnPromedioPreparatoriaChanging(value);
					this.SendPropertyChanging();
					this._PromedioPreparatoria = value;
					this.SendPropertyChanged("PromedioPreparatoria");
					this.OnPromedioPreparatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ceneval", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Ceneval
		{
			get
			{
				return this._Ceneval;
			}
			set
			{
				if ((this._Ceneval != value))
				{
					this.OnCenevalChanging(value);
					this.SendPropertyChanging();
					this._Ceneval = value;
					this.SendPropertyChanged("Ceneval");
					this.OnCenevalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPreparatoria", DbType="Int")]
		public System.Nullable<int> idPreparatoria
		{
			get
			{
				return this._idPreparatoria;
			}
			set
			{
				if ((this._idPreparatoria != value))
				{
					this.OnidPreparatoriaChanging(value);
					this.SendPropertyChanging();
					this._idPreparatoria = value;
					this.SendPropertyChanged("idPreparatoria");
					this.OnidPreparatoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="VarChar(20)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(50)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this.OnRFCChanging(value);
					this.SendPropertyChanging();
					this._RFC = value;
					this.SendPropertyChanged("RFC");
					this.OnRFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURP", DbType="VarChar(50)")]
		public string CURP
		{
			get
			{
				return this._CURP;
			}
			set
			{
				if ((this._CURP != value))
				{
					this.OnCURPChanging(value);
					this.SendPropertyChanging();
					this._CURP = value;
					this.SendPropertyChanged("CURP");
					this.OnCURPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro", DbType="VarChar(50)")]
		public string Seguro
		{
			get
			{
				return this._Seguro;
			}
			set
			{
				if ((this._Seguro != value))
				{
					this.OnSeguroChanging(value);
					this.SendPropertyChanging();
					this._Seguro = value;
					this.SendPropertyChanged("Seguro");
					this.OnSeguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoSeguro", DbType="VarChar(50)")]
		public string TipoSeguro
		{
			get
			{
				return this._TipoSeguro;
			}
			set
			{
				if ((this._TipoSeguro != value))
				{
					this.OnTipoSeguroChanging(value);
					this.SendPropertyChanging();
					this._TipoSeguro = value;
					this.SendPropertyChanged("TipoSeguro");
					this.OnTipoSeguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LugarOrigen", DbType="VarChar(50)")]
		public string LugarOrigen
		{
			get
			{
				return this._LugarOrigen;
			}
			set
			{
				if ((this._LugarOrigen != value))
				{
					this.OnLugarOrigenChanging(value);
					this.SendPropertyChanging();
					this._LugarOrigen = value;
					this.SendPropertyChanged("LugarOrigen");
					this.OnLugarOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMunicipio", DbType="Int")]
		public System.Nullable<int> idMunicipio
		{
			get
			{
				return this._idMunicipio;
			}
			set
			{
				if ((this._idMunicipio != value))
				{
					this.OnidMunicipioChanging(value);
					this.SendPropertyChanging();
					this._idMunicipio = value;
					this.SendPropertyChanged("idMunicipio");
					this.OnidMunicipioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(150)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tutor", DbType="VarChar(80)")]
		public string tutor
		{
			get
			{
				return this._tutor;
			}
			set
			{
				if ((this._tutor != value))
				{
					this.OntutorChanging(value);
					this.SendPropertyChanging();
					this._tutor = value;
					this.SendPropertyChanged("tutor");
					this.OntutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionTutor", DbType="VarChar(150)")]
		public string direccionTutor
		{
			get
			{
				return this._direccionTutor;
			}
			set
			{
				if ((this._direccionTutor != value))
				{
					this.OndireccionTutorChanging(value);
					this.SendPropertyChanging();
					this._direccionTutor = value;
					this.SendPropertyChanged("direccionTutor");
					this.OndireccionTutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefonoTutor", DbType="VarChar(20)")]
		public string telefonoTutor
		{
			get
			{
				return this._telefonoTutor;
			}
			set
			{
				if ((this._telefonoTutor != value))
				{
					this.OntelefonoTutorChanging(value);
					this.SendPropertyChanging();
					this._telefonoTutor = value;
					this.SendPropertyChanged("telefonoTutor");
					this.OntelefonoTutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPrepa", DbType="Int")]
		public System.Nullable<int> idPrepa
		{
			get
			{
				return this._idPrepa;
			}
			set
			{
				if ((this._idPrepa != value))
				{
					this.OnidPrepaChanging(value);
					this.SendPropertyChanging();
					this._idPrepa = value;
					this.SendPropertyChanged("idPrepa");
					this.OnidPrepaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idSemestre", DbType="Int")]
		public System.Nullable<int> idSemestre
		{
			get
			{
				return this._idSemestre;
			}
			set
			{
				if ((this._idSemestre != value))
				{
					this.OnidSemestreChanging(value);
					this.SendPropertyChanging();
					this._idSemestre = value;
					this.SendPropertyChanged("idSemestre");
					this.OnidSemestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Promedio", DbType="Float")]
		public System.Nullable<double> Promedio
		{
			get
			{
				return this._Promedio;
			}
			set
			{
				if ((this._Promedio != value))
				{
					this.OnPromedioChanging(value);
					this.SendPropertyChanging();
					this._Promedio = value;
					this.SendPropertyChanged("Promedio");
					this.OnPromedioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cohorte", DbType="VarChar(50)")]
		public string Cohorte
		{
			get
			{
				return this._Cohorte;
			}
			set
			{
				if ((this._Cohorte != value))
				{
					this.OnCohorteChanging(value);
					this.SendPropertyChanging();
					this._Cohorte = value;
					this.SendPropertyChanged("Cohorte");
					this.OnCohorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desertor", DbType="Bit")]
		public System.Nullable<bool> desertor
		{
			get
			{
				return this._desertor;
			}
			set
			{
				if ((this._desertor != value))
				{
					this.OndesertorChanging(value);
					this.SendPropertyChanging();
					this._desertor = value;
					this.SendPropertyChanged("desertor");
					this.OndesertorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezagado", DbType="Bit")]
		public System.Nullable<bool> rezagado
		{
			get
			{
				return this._rezagado;
			}
			set
			{
				if ((this._rezagado != value))
				{
					this.OnrezagadoChanging(value);
					this.SendPropertyChanging();
					this._rezagado = value;
					this.SendPropertyChanged("rezagado");
					this.OnrezagadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baja", DbType="Bit")]
		public System.Nullable<bool> baja
		{
			get
			{
				return this._baja;
			}
			set
			{
				if ((this._baja != value))
				{
					this.OnbajaChanging(value);
					this.SendPropertyChanging();
					this._baja = value;
					this.SendPropertyChanged("baja");
					this.OnbajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoCarrera", DbType="VarChar(50)")]
		public string GrupoCarrera
		{
			get
			{
				return this._GrupoCarrera;
			}
			set
			{
				if ((this._GrupoCarrera != value))
				{
					this.OnGrupoCarreraChanging(value);
					this.SendPropertyChanging();
					this._GrupoCarrera = value;
					this.SendPropertyChanged("GrupoCarrera");
					this.OnGrupoCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulado", DbType="VarChar(2)")]
		public string Titulado
		{
			get
			{
				return this._Titulado;
			}
			set
			{
				if ((this._Titulado != value))
				{
					this.OnTituladoChanging(value);
					this.SendPropertyChanging();
					this._Titulado = value;
					this.SendPropertyChanged("Titulado");
					this.OnTituladoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Egresado", DbType="VarChar(2)")]
		public string Egresado
		{
			get
			{
				return this._Egresado;
			}
			set
			{
				if ((this._Egresado != value))
				{
					this.OnEgresadoChanging(value);
					this.SendPropertyChanging();
					this._Egresado = value;
					this.SendPropertyChanged("Egresado");
					this.OnEgresadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eficiencia_titulacion", DbType="VarChar(2)")]
		public string Eficiencia_titulacion
		{
			get
			{
				return this._Eficiencia_titulacion;
			}
			set
			{
				if ((this._Eficiencia_titulacion != value))
				{
					this.OnEficiencia_titulacionChanging(value);
					this.SendPropertyChanging();
					this._Eficiencia_titulacion = value;
					this.SendPropertyChanged("Eficiencia_titulacion");
					this.OnEficiencia_titulacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicio_social", DbType="VarChar(2)")]
		public string Servicio_social
		{
			get
			{
				return this._Servicio_social;
			}
			set
			{
				if ((this._Servicio_social != value))
				{
					this.OnServicio_socialChanging(value);
					this.SendPropertyChanging();
					this._Servicio_social = value;
					this.SendPropertyChanged("Servicio_social");
					this.OnServicio_socialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Practicas", DbType="VarChar(2)")]
		public string Practicas
		{
			get
			{
				return this._Practicas;
			}
			set
			{
				if ((this._Practicas != value))
				{
					this.OnPracticasChanging(value);
					this.SendPropertyChanging();
					this._Practicas = value;
					this.SendPropertyChanged("Practicas");
					this.OnPracticasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.folios_extras")]
	public partial class folios_extras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _folio;
		
		private string _cohorte;
		
		private int _periodo;
		
		private int _grupo;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private System.Nullable<int> _carrera;
		
		private System.Nullable<int> _materia;
		
		private System.Nullable<int> _maestro;
		
		private string _tipo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfolioChanging(int value);
    partial void OnfolioChanged();
    partial void OncohorteChanging(string value);
    partial void OncohorteChanged();
    partial void OnperiodoChanging(int value);
    partial void OnperiodoChanged();
    partial void OngrupoChanging(int value);
    partial void OngrupoChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OncarreraChanging(System.Nullable<int> value);
    partial void OncarreraChanged();
    partial void OnmateriaChanging(System.Nullable<int> value);
    partial void OnmateriaChanged();
    partial void OnmaestroChanging(System.Nullable<int> value);
    partial void OnmaestroChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    #endregion
		
		public folios_extras()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int folio
		{
			get
			{
				return this._folio;
			}
			set
			{
				if ((this._folio != value))
				{
					this.OnfolioChanging(value);
					this.SendPropertyChanging();
					this._folio = value;
					this.SendPropertyChanged("folio");
					this.OnfolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cohorte", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cohorte
		{
			get
			{
				return this._cohorte;
			}
			set
			{
				if ((this._cohorte != value))
				{
					this.OncohorteChanging(value);
					this.SendPropertyChanging();
					this._cohorte = value;
					this.SendPropertyChanged("cohorte");
					this.OncohorteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="Int NOT NULL")]
		public int periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this.OnperiodoChanging(value);
					this.SendPropertyChanging();
					this._periodo = value;
					this.SendPropertyChanged("periodo");
					this.OnperiodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="Int NOT NULL")]
		public int grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this.OngrupoChanging(value);
					this.SendPropertyChanging();
					this._grupo = value;
					this.SendPropertyChanged("grupo");
					this.OngrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrera", DbType="Int")]
		public System.Nullable<int> carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				if ((this._carrera != value))
				{
					this.OncarreraChanging(value);
					this.SendPropertyChanging();
					this._carrera = value;
					this.SendPropertyChanged("carrera");
					this.OncarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia", DbType="Int")]
		public System.Nullable<int> materia
		{
			get
			{
				return this._materia;
			}
			set
			{
				if ((this._materia != value))
				{
					this.OnmateriaChanging(value);
					this.SendPropertyChanging();
					this._materia = value;
					this.SendPropertyChanged("materia");
					this.OnmateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro", DbType="Int")]
		public System.Nullable<int> maestro
		{
			get
			{
				return this._maestro;
			}
			set
			{
				if ((this._maestro != value))
				{
					this.OnmaestroChanging(value);
					this.SendPropertyChanging();
					this._maestro = value;
					this.SendPropertyChanged("maestro");
					this.OnmaestroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewAlumnos")]
	public partial class ViewAlumnos
	{
		
		private string _CUENTA;
		
		private string _NOMBRE;
		
		private string _Cohorte;
		
		private System.Nullable<int> _SEMESTRE;
		
		private System.Nullable<int> _GRUPO;
		
		private System.Nullable<int> _CARRERA;
		
		private string _turno;
		
		private System.Nullable<bool> _desertor;
		
		private System.Nullable<bool> _baja;
		
		private System.Nullable<bool> _rezagado;
		
		private string _Titulado;
		
		private string _Egresado;
		
		private string _Eficiencia_titulacion;
		
		private string _Servicio_social;
		
		private string _Practicas;
		
		private string _GrupoCarrera;
		
		public ViewAlumnos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUENTA", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string CUENTA
		{
			get
			{
				return this._CUENTA;
			}
			set
			{
				if ((this._CUENTA != value))
				{
					this._CUENTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cohorte", DbType="VarChar(50)")]
		public string Cohorte
		{
			get
			{
				return this._Cohorte;
			}
			set
			{
				if ((this._Cohorte != value))
				{
					this._Cohorte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEMESTRE", DbType="Int")]
		public System.Nullable<int> SEMESTRE
		{
			get
			{
				return this._SEMESTRE;
			}
			set
			{
				if ((this._SEMESTRE != value))
				{
					this._SEMESTRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPO", DbType="Int")]
		public System.Nullable<int> GRUPO
		{
			get
			{
				return this._GRUPO;
			}
			set
			{
				if ((this._GRUPO != value))
				{
					this._GRUPO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARRERA", DbType="Int")]
		public System.Nullable<int> CARRERA
		{
			get
			{
				return this._CARRERA;
			}
			set
			{
				if ((this._CARRERA != value))
				{
					this._CARRERA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno", DbType="VarChar(10)")]
		public string turno
		{
			get
			{
				return this._turno;
			}
			set
			{
				if ((this._turno != value))
				{
					this._turno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_desertor", DbType="Bit")]
		public System.Nullable<bool> desertor
		{
			get
			{
				return this._desertor;
			}
			set
			{
				if ((this._desertor != value))
				{
					this._desertor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baja", DbType="Bit")]
		public System.Nullable<bool> baja
		{
			get
			{
				return this._baja;
			}
			set
			{
				if ((this._baja != value))
				{
					this._baja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezagado", DbType="Bit")]
		public System.Nullable<bool> rezagado
		{
			get
			{
				return this._rezagado;
			}
			set
			{
				if ((this._rezagado != value))
				{
					this._rezagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulado", DbType="VarChar(2)")]
		public string Titulado
		{
			get
			{
				return this._Titulado;
			}
			set
			{
				if ((this._Titulado != value))
				{
					this._Titulado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Egresado", DbType="VarChar(2)")]
		public string Egresado
		{
			get
			{
				return this._Egresado;
			}
			set
			{
				if ((this._Egresado != value))
				{
					this._Egresado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eficiencia_titulacion", DbType="VarChar(2)")]
		public string Eficiencia_titulacion
		{
			get
			{
				return this._Eficiencia_titulacion;
			}
			set
			{
				if ((this._Eficiencia_titulacion != value))
				{
					this._Eficiencia_titulacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Servicio_social", DbType="VarChar(2)")]
		public string Servicio_social
		{
			get
			{
				return this._Servicio_social;
			}
			set
			{
				if ((this._Servicio_social != value))
				{
					this._Servicio_social = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Practicas", DbType="VarChar(2)")]
		public string Practicas
		{
			get
			{
				return this._Practicas;
			}
			set
			{
				if ((this._Practicas != value))
				{
					this._Practicas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoCarrera", DbType="VarChar(50)")]
		public string GrupoCarrera
		{
			get
			{
				return this._GrupoCarrera;
			}
			set
			{
				if ((this._GrupoCarrera != value))
				{
					this._GrupoCarrera = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReprobadosFoliosOrdinarios")]
	public partial class ReprobadosFoliosOrdinarios
	{
		
		private string _cuenta;
		
		private string _nombre;
		
		private double _calificacion;
		
		private int _folio;
		
		private System.Nullable<int> _carrera;
		
		private int _periodo;
		
		private System.Nullable<int> _materia;
		
		private string _cohorte;
		
		private int _grupo;
		
		public ReprobadosFoliosOrdinarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string cuenta
		{
			get
			{
				return this._cuenta;
			}
			set
			{
				if ((this._cuenta != value))
				{
					this._cuenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Float NOT NULL")]
		public double calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this._calificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int NOT NULL")]
		public int folio
		{
			get
			{
				return this._folio;
			}
			set
			{
				if ((this._folio != value))
				{
					this._folio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carrera", DbType="Int")]
		public System.Nullable<int> carrera
		{
			get
			{
				return this._carrera;
			}
			set
			{
				if ((this._carrera != value))
				{
					this._carrera = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodo", DbType="Int NOT NULL")]
		public int periodo
		{
			get
			{
				return this._periodo;
			}
			set
			{
				if ((this._periodo != value))
				{
					this._periodo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia", DbType="Int")]
		public System.Nullable<int> materia
		{
			get
			{
				return this._materia;
			}
			set
			{
				if ((this._materia != value))
				{
					this._materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cohorte", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cohorte
		{
			get
			{
				return this._cohorte;
			}
			set
			{
				if ((this._cohorte != value))
				{
					this._cohorte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupo", DbType="Int NOT NULL")]
		public int grupo
		{
			get
			{
				return this._grupo;
			}
			set
			{
				if ((this._grupo != value))
				{
					this._grupo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cal_extras")]
	public partial class cal_extras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_calificacion;
		
		private int _folio;
		
		private string _cuenta;
		
		private string _nombre;
		
		private double _calificacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_calificacionChanging(int value);
    partial void Onid_calificacionChanged();
    partial void OnfolioChanging(int value);
    partial void OnfolioChanged();
    partial void OncuentaChanging(string value);
    partial void OncuentaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncalificacionChanging(double value);
    partial void OncalificacionChanged();
    #endregion
		
		public cal_extras()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_calificacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_calificacion
		{
			get
			{
				return this._id_calificacion;
			}
			set
			{
				if ((this._id_calificacion != value))
				{
					this.Onid_calificacionChanging(value);
					this.SendPropertyChanging();
					this._id_calificacion = value;
					this.SendPropertyChanged("id_calificacion");
					this.Onid_calificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_folio", DbType="Int NOT NULL")]
		public int folio
		{
			get
			{
				return this._folio;
			}
			set
			{
				if ((this._folio != value))
				{
					this.OnfolioChanging(value);
					this.SendPropertyChanging();
					this._folio = value;
					this.SendPropertyChanged("folio");
					this.OnfolioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuenta", DbType="VarChar(9) NOT NULL", CanBeNull=false)]
		public string cuenta
		{
			get
			{
				return this._cuenta;
			}
			set
			{
				if ((this._cuenta != value))
				{
					this.OncuentaChanging(value);
					this.SendPropertyChanging();
					this._cuenta = value;
					this.SendPropertyChanged("cuenta");
					this.OncuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion", DbType="Float NOT NULL")]
		public double calificacion
		{
			get
			{
				return this._calificacion;
			}
			set
			{
				if ((this._calificacion != value))
				{
					this.OncalificacionChanging(value);
					this.SendPropertyChanging();
					this._calificacion = value;
					this.SendPropertyChanged("calificacion");
					this.OncalificacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
